controller_list:
  - name: l_arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - l_joint1
      - l_joint2
      - l_joint3
      - l_joint4
      - l_joint5
      - l_joint6
  - name: r_arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - r_joint1
      - r_joint2
      - r_joint3
      - r_joint4
      - r_joint5
      - r_joint6


