l_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - l_Joint_finger1
    - l_Joint_finger2
  gains:
    l_Joint_finger1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_Joint_finger2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
r_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - r_Joint_finger1
    - r_Joint_finger2
  gains:
    r_Joint_finger1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_Joint_finger2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

