l_arm:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - l_joint1
    - l_joint2
    - l_joint3
    - l_joint4
    - l_joint5
    - l_joint6
    - l_joint7
  gains:
    l_joint1: {p: 1000.0, i: 0.0, d: 0.1}
    l_joint2: {p: 1000.0, i: 0.0, d: 0.1}
    l_joint3: {p: 1000.0, i: 0.0, d: 0.1}
    l_joint4: {p: 1000.0, i: 0.0, d: 0.1}
    l_joint5: {p: 1000.0, i: 0.0, d: 0.1}
    l_joint6: {p: 1000.0, i: 0.0, d: 0.1}
    l_joint7: {p: 1000.0, i: 0.0, d: 0.1}
  constraints:
    stopped_velocity_tolerance:0.0

r_arm:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - r_joint1
    - r_joint2
    - r_joint3
    - r_joint4
    - r_joint5
    - r_joint6
    - r_joint7
  gains:
    r_joint1: {p: 1000.0, i: 0.0, d: 0.1}
    r_joint2: {p: 1000.0, i: 0.0, d: 0.1}
    r_joint3: {p: 1000.0, i: 0.0, d: 0.1}
    r_joint4: {p: 1000.0, i: 0.0, d: 0.1}
    r_joint5: {p: 1000.0, i: 0.0, d: 0.1}
    r_joint6: {p: 1000.0, i: 0.0, d: 0.1}
    r_joint7: {p: 1000.0, i: 0.0, d: 0.1}
  constraints:
    stopped_velocity_tolerance:0.0
